### ISSUE TITLE
PPTV 直播

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#580]
有人在 Google Group 上问 PPTV 的问题
https://groups.google.com/forum/#!topic/unblock-youku/XzDFJVstBXY

我试了下
首先是这个节目时间表 http://live.pptv.com/list/sports_program/_1-43-.html
不用代理显示不出来内容

然后重播的页面 http://v.pptv.com/show/wWN6ibWHHN3XYVr4.html
不用代理会显示“节目信息加载异常”

然后是直播的页面例如 http://v.pptv.com/show/XQlw7la8LGrNS7M.html
就算用上全局代理也没用，比较奇怪

> ![screen shot 2016-01-31 at 4 12 22 pm](https://cloud.githubusercontent.com/assets/928905/12706260/843f51d8-c835-11e5-8b63-9324e0e597be.png)

**Comment by zhuzhuor** [comment]
试了下，不是直播的视频其实也有问题

http://v.pptv.com/show/iaX5y8VmicL23QTrY.html?rcc_src=X1
http://v.pptv.com/show/3aL7eOBGtvRX1T0.html?rcc_src=X2

**Comment by yanggis** [comment]
节目那个网页可以加载，就是超级慢，因为PPTV的服务器很少，只有那一两台服务器，从国外连接超级慢。最下面那个两个Links也是播放不了，但是基本可以断定是PPTV服务器抽风引起的。

**Comment by mc16888** [comment]
I found the problem related to a cookie key named "ppi", if you have this key, when you play the video, it will include this key in request and video will fail to play.

For example, http://v.pptv.com/show/wWN6ibWHHN3XYVr4.html
First I clear all the cookies for pptv.com and play above video, you can see there is no ppi= in the request url and the video plays without problem
![pptv11](https://cloud.githubusercontent.com/assets/6530873/12785889/90edb794-cac9-11e5-9c96-ce86cb72a936.jpg)

Then I refresh the link, since you already visit the pptv.com, that ppi key is in your browser now, the request will include this key and video fail to play.
![pptv22](https://cloud.githubusercontent.com/assets/6530873/12786099/7e5ef4d4-caca-11e5-8616-5bf8e4e58950.jpg)

if you delete the ppi key and refresh it will play again.

**Comment by mc16888** [comment]
原來要加這一條規則, 用wireshark才capture到. 把這一個URL加入代理之後,上面的視頻都可已成功播放.

http://tools.aplusapi.pptv.com/get_ppi?cb=wn

節目列表的話, 我加了這一個 URL 進代理才有內容, 不過要等很久才會有內容.

http://live.pptv.com/api/subject_list?xxxxxxxxxxxxxxxxxxxx

**Comment by zhuzhuor** [comment]
@mc16888 给力！非常感谢！欢迎提交个 pull request
